# Generated by Django 5.2.15 on 2026-06-28 19:27

import dashboard.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('ANALYST', 'Analyst')], db_index=True, default='ANALYST', help_text="Determines the user's access level in the SOC dashboard.", max_length=10)),
                ('email', models.EmailField(help_text='Required. Used for notifications and account recovery.', max_length=254, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'dashboard_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('file_path', models.FileField(help_text='Path to the uploaded .evtx file in MEDIA_ROOT.', upload_to=dashboard.models._upload_to_evtx, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['evtx'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current processing state of the analysis job.', max_length=10)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the job failed. Empty on success.')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the file was uploaded.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the analysis finished (success or failure).', null=True)),
                ('total_samples', models.PositiveIntegerField(default=0, help_text='Total number of time windows analyzed.')),
                ('total_anomalies', models.PositiveIntegerField(default=0, help_text='Number of time windows flagged as anomalous.')),
                ('user', models.ForeignKey(help_text='The analyst who initiated this analysis.', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Job',
                'verbose_name_plural': 'Analysis Jobs',
                'db_table': 'dashboard_analysisjob',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(help_text='Start timestamp of the anomalous time window.')),
                ('computer_name', models.CharField(blank=True, default='', help_text='Hostname of the machine where the anomaly was detected.', max_length=255)),
                ('anomaly_score', models.FloatField(db_index=True, help_text='Raw decision_function score from Isolation Forest. More negative = more anomalous.')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, help_text='SOC-friendly severity classification based on anomaly_score.', max_length=10)),
                ('feature_data', models.JSONField(default=dict, help_text="Dictionary of the 15 feature values for this time window. Keys match Config.FEATURE_COLUMNS (e.g., 'failed_logins', 'process_creation_events').")),
                ('rag_explanation', models.TextField(blank=True, default='', help_text='LLM-generated incident explanation. Populated by the RAG layer in Phase 14. Empty until then.')),
                ('job', models.ForeignKey(help_text='The analysis job that detected this anomaly.', on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='dashboard.analysisjob')),
            ],
            options={
                'verbose_name': 'Anomaly',
                'verbose_name_plural': 'Anomalies',
                'db_table': 'dashboard_anomaly',
                'ordering': ['anomaly_score'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('UPLOAD', 'File Upload'), ('VIEW', 'View Results'), ('DELETE', 'Delete Record'), ('EXPORT', 'Export Report')], db_index=True, help_text='The type of action performed.', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the action.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action was performed.')),
                ('job', models.ForeignKey(blank=True, help_text='The analysis job related to this action (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dashboard.analysisjob')),
                ('user', models.ForeignKey(help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'dashboard_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'uploaded_at'], name='idx_job_status_uploaded'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['severity', 'anomaly_score'], name='idx_anomaly_severity_score'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['job', 'severity'], name='idx_anomaly_job_severity'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='idx_audit_action_created'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='idx_audit_user_created'),
        ),
    ]
